name: Pull_Request_Tests

on:
  pull_request:
    branches:
    - master
    - dev

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'run yarn'
      run: |
        yarn install
        yarn run build
        yarn run test
